#!/bin/sh

ARG_CPU=FALSE
ARG_MEM=FALSE

if [ -z $1 ] ; then
  ARG_CPU=TRUE
  ARG_MEM=TRUE
fi

while [ $# -gt 0 ] ; do
  case $1 in
    --cpu|-c) ARG_CPU=TRUE
    ;;
    --mem|-m) ARG_MEM=TRUE
    ;;
    *) echo "error" >&2
       exit 1
    ;;
  esac
  shift
done

if [ $ARG_CPU = TRUE ] ; then
  top -bn1 | awk '/Cpu\(s\):/{gsub(/[^0-9. ]/,"");printf("C %.1f%%\n", 100-$4)}'
fi

if [ $ARG_MEM = TRUE ] ; then
  top -bn1 | awk '/Mem:/{gsub(/[^0-9 ]/,"");printf("M %.1f%%\n",$2/$1*100)}'
fi
